name: Compilar panelsrv para mipsel

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Reemplazar TOKEN desde secreto
        
        env:
          PANELSRV_TOKEN: ${{ secrets.PANELSRV_TOKEN }}
        
        if: env.PANELSRV_TOKEN != ''
        
        run: sed -i "s/change/$PANELSRV_TOKEN/g" panelsrv.c

      - name: Descargar toolchain mipsel-linux-musl
        run: |
          curl -L --retry 3 -o mipsel-linux-musl-cross.tgz https://musl.cc/mipsel-linux-musl-cross.tgz
          tar xzf mipsel-linux-musl-cross.tgz

      - name: Compilar estático para mipsel
        run: |
          export PATH="${{ github.workspace }}/mipsel-linux-musl-cross/bin:$PATH"
          mipsel-linux-musl-gcc -static -O2 -o panelsrv panelsrv.c
          file panelsrv

      - name: Subir binario como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: panelsrv-mipsel
          path: panelsrv
