name: Compilar panelsrv para mipsel

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: Reemplazar TOKEN desde secreto
        env:
          PANELSRV_TOKEN: ${{ secrets.PANELSRV_TOKEN }}
        run: |
          if [ -n "$PANELSRV_TOKEN" ]; then
            echo "Reemplazando token en el código..."
            sed -i "s/change/$PANELSRV_TOKEN/g" panelsrv.c
          fi

      - name: Compilar estático para mipsel
        run: |
          zig cc -target mipsel-linux-musl -static -O2 -o panelsrv panelsrv.c
          file panelsrv

      - name: Subir binario como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: panelsrv-mipsel
          path: panelsrv
